skin: "/assets/css/skins/default.css"
locale: en-US
title: "Tributes for Surekha Pillai"
description: "Surekha had once joked about wanting to hear the nice things people would say about her once she was gone. So here’s a small collection — maybe she’ll get to read them from wherever she is."
baseurl: "/" # the subpath of your site, e.g. "/blog"
url: "https://surekhapillai.com" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
logo: # path of site logo, e.g. "/images/logo.png"
date_format: "%B %-d, %Y"
read_time: # reading time estimates, e.g. true
words_per_minute: # 200
mathjax:
  enable: # MathJax equations, e.g. true, false (default)
  combo: # "tex-svg" (default), "tex-mml-chtml", etc.: docs.mathjax.org/en/latest/web/components/combined.html
  tags: # "none", "ams" (default), "all"
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
google_analytics: # Google Analytics id, e.g. "UA-NNNNNNNN-N"
disqus:
  shortname: # Disqus shortname, e.g. "my_disqus_shortname"
twitter:
  username: # site's Twitter username, e.g. "mmistakes"

# Liquid
liquid:
  error_mode: strict

# Build settings
permalink: /:categories/:title/
markdown: kramdown
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
# paginate: 10
# paginate_path: /page:num/

# Search
search_full_content: false # can have performance implications for large sites

# Taxonomy pages
# category_archive_path: "/categories/#"
# tag_archive_path: "/tags/#"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Front Matter Defaults
defaults:
  # Posts defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: false
  - scope:
      path: "_drafts"
      type: posts
    values:
      layout: post
      share: false

# Site Author
author:
  name:
  picture:
  email:
  twitter:
  links:
    - title:
      url:
      icon:

# Footer Links
footer_links:
  # - title: Feed
  #   url: atom.xml
  #   icon: fas fa-rss-square
  # - title: GitHub
  #   url: https://github.com/surekhapillai/surekhapillai
  #   icon: fab fa-github
